// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    DrawList: typeof import('./components/recordList/drawList.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    ModifyTime: typeof import('./components/modifyTime/modifyTime.vue')['default']
    README: typeof import('./components/README.md')['default']
    RecordsList: typeof import('./components/records/RecordsList.vue')['default']
    SignList: typeof import('./components/recordList/signList.vue')['default']
    StuList: typeof import('./components/recordList/stuList.vue')['default']
    VoteList: typeof import('./components/recordList/voteList.vue')['default']
  }
}

export { }
